In [158]:
#导入包
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [51]:
from sklearn import datasets
import random

In [8]:
iris = datasets.load_iris()

In [12]:
iris.data[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [26]:
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,
                                                 train_size=0.8,random_state=12)

In [27]:
len(x_train)

120

In [28]:
x_test.shape

(30, 4)

In [38]:
#建模
clf = GaussianNB()
clf.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [40]:
y_pred = clf.predict(x_test)

In [42]:
scores = accuracy_score(y_true=y_test,y_pred=y_pred)
scores

0.9666666666666667

In [43]:
%ls

iris.txt*              朴素贝叶斯.ipynb


In [50]:
#数据导入
dataset = pd.read_csv('iris.txt',delimiter=',',header=None)
dataset

0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [138]:
#切分训练集和测试集

def cutAndshuffle_dataset(dataset,rate=0.8):
    m = dataset.shape[0]
    n = dataset.shape[1]
    indexs = list(dataset.index)
    random.shuffle(indexs)
    dataset.index = indexs
    train_size = int(rate*m)
    x_train = dataset.loc[range(train_size),:]
    x_test = dataset.loc[range(train_size,m),:]
    x_test.index = range(m-train_size)
    # print("切分完成")
    return x_train,x_train.iloc[:,-1],x_test,x_test.iloc[:,-1]

In [151]:
x_train,y_train,x_test,y_test = cutAndshuffle_dataset(dataset)
x_train

切分完成


0    1    2    3                4
0    5.7  2.5  5.0  2.0   Iris-virginica
1    5.2  4.1  1.5  0.1      Iris-setosa
2    5.7  2.8  4.1  1.3  Iris-versicolor
3    5.2  3.5  1.5  0.2      Iris-setosa
4    5.6  3.0  4.5  1.5  Iris-versicolor
..   ...  ...  ...  ...              ...
115  5.0  3.4  1.6  0.4      Iris-setosa
116  5.8  2.7  5.1  1.9   Iris-virginica
117  6.7  3.1  4.4  1.4  Iris-versicolor
118  6.7  3.3  5.7  2.5   Iris-virginica
119  6.0  2.9  4.5  1.5  Iris-versicolor

[120 rows x 5 columns]

In [231]:
#建模 构建高斯朴素贝叶斯分类器
def train_nbclassifier(x_train,x_test):
    labels = y_train.value_counts().index
    m = x_train.shape[0]
    n = x_train.shape[1]
    all_means = []
    all_stds = []
    for label in labels:
        x_temp = x_train[x_train.iloc[:,-1] == label]
        x_mean = x_temp.mean()
        x_std = np.sum(((x_temp.iloc[:,:-1] - x_mean)**2)/x_temp.shape[0])
        all_means.append(x_mean)
        all_stds.append(x_std)
    means = pd.DataFrame(all_means,index = labels)
    stds = pd.DataFrame(all_stds,index=labels)
    results = []
    # print(stds)
    for i in range(x_test.shape[0]):
        item = x_test.iloc[i,:-1].tolist()
        prob = np.exp(-1*(item-means)/(2*stds))/(np.sqrt(2*np.pi*stds))
        # probs.append(prob)
        item_p = 1.0
        # print(prob)
        for j in range(n-1):
            item_p *= prob.iloc[:,j]
            #print(item_p)
        results.append(np.argmax(item_p))
    # print(results)
    # 计算准确率
    socres = accuracy_score(x_test.iloc[:,-1],results)
    # print(scores)
    return scores
    
# train_nbclassifier(x_train,x_test)

In [155]:
#测试模型效果

In [232]:
def test_performance(dataset):
    scores = 0.0
    i = 0
    while i <10:
        x_train,y_train,x_test,y_test = cutAndshuffle_dataset(dataset)
        score = train_nbclassifier(x_train,x_test)
        print(score)
        i += 1

test_performance(dataset)

切分完成
0.9666666666666667
切分完成
0.9666666666666667
切分完成
0.9666666666666667
切分完成
0.9666666666666667
切分完成
0.9666666666666667
切分完成
0.9666666666666667
切分完成
0.9666666666666667
切分完成
0.9666666666666667
切分完成
0.9666666666666667
切分完成
0.9666666666666667


In [234]:
# 文档分类

"""
1. 构建词向量
2. 构建词汇表
3. 生成训练集词向量列表
4. 朴素贝叶斯分类器训练
5. 模型测试
6. 模型优化
"""

'\n1. 构建词向量\n2. 构建词汇表\n3. 生成训练集词向量列表\n4. 朴素贝叶斯分类器训练\n5. 模型测试\n6. 模型优化\n'

In [242]:
# 1. 创建实验数据集
def build_dataset():
    doc_dataset=[
        ['my','dog','has','flea','problems','help','please'],
        ['maybe','not','take','him','to','dog','park','stupid'],
        ['my','dalmation','is','so','cute','I','love','him'],
        ['stop','posting','stupid','worthless','garbage'],
        ['mr','licks','ate','my','steak','how','to','stop','him'],
        ['quit','buying','worthlsess','dog','food','stupid']
    ]
    doc_classVec=[0,1,0,1,0,1] #0代表正常言论，1代表侮辱性文字
    return doc_dataset,doc_classVec

In [245]:
doc_dataset = None
doc_classVec = None
doc_dataset,doc_classVec = build_dataset()
doc_classVec

[0, 1, 0, 1, 0, 1]

In [290]:
# 2. 生成词汇表
def build_voc_table(doc_dataset):
    voc_list = set()
    freq_dict = {}
#     for i in range(len(doc_dataset)):
#         for j in doc_dataset[i]:
#             if freq_dict.get(j):
#                 freq_dict[j] += 1
#             else:
#                 freq_dict[j] = 1
#                 voc_list.append(j)
    for i in doc_dataset:
        voc_list  = voc_list | set(i)
    voc_list = list(voc_list)
    return voc_list,freq_dict

In [292]:
voc_list = []
freq_dict = {}
voc_list,freq_dict = build_voc_table(doc_dataset)
voc_list

['has',
 'dog',
 'is',
 'not',
 'I',
 'quit',
 'problems',
 'so',
 'to',
 'mr',
 'how',
 'help',
 'stop',
 'garbage',
 'maybe',
 'my',
 'dalmation',
 'cute',
 'steak',
 'worthless',
 'stupid',
 'please',
 'ate',
 'love',
 'take',
 'licks',
 'posting',
 'flea',
 'food',
 'worthlsess',
 'buying',
 'park',
 'him']

In [304]:
# 3. 生成句子向量
def build_senvec(voc_list,sens):
    m = len(voc_list)
    n = len(sens)
    sensVec = []
    for k in range(n):
#       senVec = np.zeros(m)
        senVec = [0]*m
#         senVec.reshape(1,m)
        for i in range(len(sens[k])):
            word = sens[k][i]
            idx = voc_list.index(word)
            senVec[idx] =1
#       print(senVec)
        sensVec.append(senVec)
    return sensVec

In [310]:
sensVec = None
sensVec = build_senvec(voc_list,doc_dataset)
len(sensVec)

6

In [402]:
a = np.array([1,2,3,4,5])
b = [2,2,3,4,1]
b.index[2]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [383]:
# 4. 构建分类器
from functools import reduce
"""
1. 计算所有文档中是垃圾文档的概率（先验）
2. 分别计算垃圾文档与非垃圾文档的特征的条件概率
"""
def train_docNBclassifier(x_train,y_train):
    count = 0 
    m = len(x_train)
    n = len(x_train[0])
#     for i in y_train:
#         if i == 1: 
#             count += 1
#     prob_0 = np.zeros(n) 
#     num0 = 0
#     prob_1 = np.zeros(n)
#     num1 = 0
    # 引入拉普拉斯平滑
    prob_0 = np.ones(n)
    prob_1 =np.ones(n)
    num0 = 2
    num1 = 2
    for i in range(m):
        if y_train[i] == 0:
            prob_0 += x_train[i]
            num0 += sum(x_train[i])
        else:
            prob_1 += x_train[i]
            num1 += sum(x_train[i])
            count += 1
#     conprob_0 = map(lambda x,y: x/y,prob_0,sum0)
    conprob_0 = np.log(prob_0/num0)
    conprob_1 = np.log(prob_1/num1)
    prior_prob = count/m
    return conprob_0,conprob_1,prior_prob

In [384]:
conprob_0,conprob_1,prior_prob = train_docNBclassifier(sensVec,doc_classVec)
conprob_0,conprob_1,prior_prob


(array([-2.56494936, -2.56494936, -2.56494936, -3.25809654, -2.56494936,
        -3.25809654, -2.56494936, -2.56494936, -2.56494936, -2.56494936,
        -2.56494936, -2.56494936, -2.56494936, -3.25809654, -3.25809654,
        -1.87180218, -2.56494936, -2.56494936, -2.56494936, -3.25809654,
        -3.25809654, -2.56494936, -2.56494936, -2.56494936, -3.25809654,
        -2.56494936, -3.25809654, -2.56494936, -3.25809654, -3.25809654,
        -3.25809654, -3.25809654, -2.15948425]),
 array([-3.04452244, -1.94591015, -3.04452244, -2.35137526, -3.04452244,
        -2.35137526, -3.04452244, -3.04452244, -2.35137526, -3.04452244,
        -3.04452244, -3.04452244, -2.35137526, -2.35137526, -2.35137526,
        -3.04452244, -3.04452244, -3.04452244, -3.04452244, -2.35137526,
        -1.65822808, -3.04452244, -3.04452244, -3.04452244, -2.35137526,
        -3.04452244, -2.35137526, -3.04452244, -2.35137526, -2.35137526,
        -2.35137526, -2.35137526, -2.35137526]),
 0.5)

In [399]:
#5. 模型测试
def classifier_test(prob0,prob1,prior_prob,x_test):
#     doc_dataset,doc_classVec = build_dataset()
#     voc_list,freq_dict = build_voc_table(doc_dataset)
#     sensVec = build_senvec(voc_list,doc_dataset)
#     testsVec = build_senvec(voc_list,x_test)
#     conprob_0,conprob_1,prior_prob = train_docNBclassifier(sensVec,doc_classVec)
#     p0 = sum(reduce(lambda x,y:x*y, x_test*prob0)*(1-prior_prob))
#     p1 = sum(reduce(lambda x,y:x*y, x_test*prob1)*prior_prob)
    # 引入拉普拉斯平滑，因为是log概率所以连乘可以直接相加
    p0 = np.sum((x_test * prob0))+ np.log(1-prior_prob)
    p1 = np.sum((x_test * prob1))+ np.log(prior_prob)
    print('p0:',p0)
    
    print('p1',p1)
    if p0 > p1:
        return 0 
    else:
        return 1

In [400]:
#注意关注维度
x_test = [['quit','buying','worthlsess','dog','food','stupid']]
testVec = build_senvec(voc_list,x_test)

In [401]:
result = classifier_test(conprob_0,conprob_1, prior_prob, testVec)

p0: -19.54857922812889
p1 -13.702786434872701


In [379]:
result

1